// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentManagement.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TalentManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentManagement.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prefix")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PositionId" }, "IX_Employees_PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PositionNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("SalaryRangeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Positions_DepartmentId");

                    b.HasIndex(new[] { "SalaryRangeId" }, "IX_Positions_SalaryRangeId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PositionDescription", b =>
                {
                    b.Property<decimal>("PdSeqNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CrmTicketNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GrdCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("Guid")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("GvtOccSeries")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GvtOrgTitleCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GvtOrgTitleEffDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GvtPayPlan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GvtPosnTitleCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GvtPosnTitleEffDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobFunction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("JobFunctionEffDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdAcquisitionPosInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdArchiveInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdBargUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdCareerLadderInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PdClassifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdClassifierCommentsText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PdClassifierHruId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdClpdGradeInterval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PdCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PdCreateId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PdEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PdEffectiveSeqNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdEvalStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdExplantnComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdFinDisclosureInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdFlsaInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdFlsaUrlText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdIaAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PdIaLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdInterdisciplinaryInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdIntro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdIpop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdLeoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdLimitationsOfUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdManagerLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdNbr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PdOldGemsJobcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdOldGemsPdNbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdOrgTitleText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PdOriginOrgCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PdOriginalEffdt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdPositionTitleText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PdReasonForSubmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdReplacePdNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdTargetGradeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdTransType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PdUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PdUpdateId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdsStateCd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PdthAssignedOwner")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PsSourceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillCd1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PdSeqNum");

                    b.ToTable("PositionDescriptions");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PositionDescriptionAudit", b =>
                {
                    b.Property<decimal>("PdAuditSeqNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CrmTicketNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GrdCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GvtOccSeries")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GvtOrgTitleCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GvtOrgTitleEffDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GvtPayPlan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GvtPosnTitleCd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GvtPosnTitleEffDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobFunction")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("JobFunctionEffDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdAcquisitionPosInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdArchiveInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdBargUnitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdCareerLadderInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PdClassifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdClassifierCommentsText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("PdClassifierHruId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdClpdGradeInterval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PdCreateId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PdEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PdEffectiveSeqNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdEvalStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdExplantnComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdFinDisclosureInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdFlsaInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdFlsaUrlText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdIaAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PdIaLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdInterdisciplinaryInd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdIntro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdIpop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdLeoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdLimitationsOfUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdManagerLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdNbr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PdOldGemsPdNbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdOrgTitleText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PdOriginOrgCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PdOriginalEffdt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdPositionTitleText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PdReasonForSubmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdReplacePdNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PdSeqNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PdTargetGradeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdTransType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PdUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PdUpdateId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PdaCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdsStateCd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PdthAssignedOwner")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PsSourceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillCd1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PdAuditSeqNum");

                    b.HasIndex("PdSeqNum");

                    b.ToTable("PositionDescriptionAudit");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.SalaryRange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MaxSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("SalaryRanges");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Employee", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Position", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.SalaryRange", "SalaryRange")
                        .WithMany("Positions")
                        .HasForeignKey("SalaryRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SalaryRange");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PositionDescriptionAudit", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.PositionDescription", "PdSeqNumNavigation")
                        .WithMany("PositionDescriptionAudit")
                        .HasForeignKey("PdSeqNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdSeqNumNavigation");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Department", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PositionDescription", b =>
                {
                    b.Navigation("PositionDescriptionAudit");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.SalaryRange", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
