using System;

namespace Enterprise.Domain.Entities.Acrs
{
    public partial class AcrsGemsPosition
    {
        public decimal AgposSeqNum { get; set; }
        public string AgpJobcode { get; set; }
        public string RegTemp { get; set; }
        public string QrePreAppMedChkupReq { get; set; }
        public string PositionSensitivity { get; set; }
        public string SecurityClearance { get; set; }
        public string Location { get; set; }
        public string QrpFullPerfLevelInd { get; set; }
        public string QrpUpwardMobilityInd { get; set; }
        public string QrpTitle38EligibilityInd { get; set; }
        public string QrpTitle38PremiumPayCd { get; set; }
        public string ReasonForDrugTestText { get; set; }
        public string QrpMdDrugTestReqInd { get; set; }
        public string QrpFirearmsAmmoInd { get; set; }
        public string QrpLatenbergAmendInd { get; set; }
        public string QrpUniformReqInd { get; set; }
        public string QrpPositionOrgCd { get; set; }
        public string QrpPositionLocation { get; set; }
        public string QreObligatedPosInd { get; set; }
        public string QreIncWeatherInd { get; set; }
        public string QrePcsAuthorizedInd { get; set; }
        public string QreAnnualPhysicalReqInd { get; set; }
        public string QreNewlyAuthPosnInd { get; set; }
        public DateTime? QreNewPosnAuthDate { get; set; }
        public string QreSurroundingLocInfoText { get; set; }
        public string RecruitmentType { get; set; }
        public string QrmSalaryExpensePosInd { get; set; }
        public string QrmBureauFundPosInd { get; set; }
        public string QrmSepApprFundPosInd { get; set; }
        public string QrmAllocationNbr { get; set; }
        public string QrmAllotmentNbr { get; set; }
        public string QrmFunctionCode { get; set; }
        public string QrmObjectCode { get; set; }
        public string AgposComments { get; set; }
        public decimal? NumOfPositions { get; set; }
        public string QrmFundType { get; set; }
        public string PositionNumber { get; set; }
        public decimal? RpaSeqNum { get; set; }
        public decimal? RpaNbr { get; set; }
        public DateTime? RpaProposedEffectiveDate { get; set; }
        public string QrpPositionTypeCode { get; set; }
        public decimal? QrpStandardHoursNbr { get; set; }
        public decimal? QrpMaxHeadCountNbr { get; set; }
        public string SalAdminPlan { get; set; }
        public string QrpPositionOccupiedCode { get; set; }
        public string GvtCompLevel { get; set; }
        public DateTime? QrpNteDate { get; set; }
        public string GvtSubAgency { get; set; }
        public string QrpFullTimeInd { get; set; }
        public string GmTeleWrk { get; set; }
        public string ReportsTo { get; set; }
        public string AgposStatus { get; set; }
        public DateTime? AgposProcessedDate { get; set; }
        public string AgposProcessedInd { get; set; }
        public string AgposGemsError { get; set; }
        public string AgposTransType { get; set; }
        public string BargUnit { get; set; }
        public DateTime? AgposTransactionDate { get; set; }
        public string GemsUserid { get; set; }
        public string WorkSchedule { get; set; }
        public string ProposedPositionNumber { get; set; }
        public string QrpOpmCertNbr { get; set; }
        public string SkillCd2 { get; set; }
        public decimal AgposCreateId { get; set; }
        public DateTime AgposCreateDate { get; set; }
        public decimal? AgposUpdateId { get; set; }
        public DateTime? AgposUpdateDate { get; set; }
        public decimal? PdSeqNum { get; set; }
        public decimal? MonHrs { get; set; }
        public decimal? TueHrs { get; set; }
        public decimal? WedHrs { get; set; }
        public decimal? ThursHrs { get; set; }
        public decimal? FriHrs { get; set; }
        public decimal? SatHrs { get; set; }
        public decimal? SunHrs { get; set; }
        public string GvtCompArea { get; set; }
        public string PsSourceCode { get; set; }
        public string CyberSecurity { get; set; }
        public string QrmOpAllowance { get; set; }
        public string QrmProject { get; set; }
        public string QrmObligationNo { get; set; }
        public string GmCybersecCd1 { get; set; }
        public string GmCybersecCd2 { get; set; }
        public string GmCybersecCd3 { get; set; }
        public string GvtOpmCertNbr { get; set; }
        public string GmPublicTrust { get; set; }
        public string DsBbfy { get; set; }
        public string DsEbfy { get; set; }
        public string DsDivBureau { get; set; }
    }
}
